<?xml version="1.0"?>
<package format="3">
  <name>pyrobopath_ros</name>
  <version>0.2.0</version>
  <description>Meta-package for pyrobopath ROS2 integration</description>
  <author email="arbogastaw@gmail.com">Alex Arbogast</author>
  <maintainer email="arbogastaw@gmail.com">Alex Arbogast</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>pyrobopath_msgs</exec_depend>
  <exec_depend>pyrobopath_execution</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
